project_id = "fvdncnxgmfzxlqtqxitl"

[functions.generate-outreach]
verify_jwt = false

[functions.fetch-dc-buildings]
verify_jwt = false

[functions.generate-nonprofit-outreach]
verify_jwt = false

[functions.refine-email]
verify_jwt = false

[functions.fetch-market-news]
verify_jwt = false

[functions.smart-drafting]
verify_jwt = false

[functions.smart-outreach]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.meeting-prep]
verify_jwt = false