-- exec_readonly_sql: Safely execute read-only SQL queries generated by the Text-to-SQL tool
-- Only allows SELECT statements, blocks all mutations
CREATE OR REPLACE FUNCTION exec_readonly_sql(query_text text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result jsonb;
  normalized text;
BEGIN
  -- Normalize: trim and lowercase for safety check
  normalized := lower(trim(query_text));

  -- Block anything that isn't a SELECT
  IF NOT (normalized LIKE 'select%' OR normalized LIKE 'with%') THEN
    RAISE EXCEPTION 'Only SELECT queries are allowed';
  END IF;

  -- Block dangerous keywords
  IF normalized ~ '(insert|update|delete|drop|alter|create|truncate|grant|revoke|copy|execute|do\s)' THEN
    RAISE EXCEPTION 'Mutation queries are not allowed';
  END IF;

  -- Execute and return as JSON array
  EXECUTE format('SELECT jsonb_agg(row_to_json(t)) FROM (%s) t', query_text) INTO result;

  RETURN COALESCE(result, '[]'::jsonb);
END;
$$;

-- Grant execute to authenticated users only
GRANT EXECUTE ON FUNCTION exec_readonly_sql(text) TO service_role;
